// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANKu2K9UvYkcfZOGL-IpjpUp2X2Z5-S94',
    appId: '1:684530111357:web:e7db3a60668ea617797214',
    messagingSenderId: '684530111357',
    projectId: 'recipe-5a6ca',
    authDomain: 'recipe-5a6ca.firebaseapp.com',
    storageBucket: 'recipe-5a6ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDaU-fuDNjtFse_Yn1_QtkYnZr1YGs5Y',
    appId: '1:684530111357:android:9456c01c84ef8174797214',
    messagingSenderId: '684530111357',
    projectId: 'recipe-5a6ca',
    storageBucket: 'recipe-5a6ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx2R-rDUc0kEu57YxJIj0U4B4nYcHc-Fg',
    appId: '1:684530111357:ios:a236b030fa7c52e5797214',
    messagingSenderId: '684530111357',
    projectId: 'recipe-5a6ca',
    storageBucket: 'recipe-5a6ca.appspot.com',
    iosBundleId: 'com.example.receipeGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx2R-rDUc0kEu57YxJIj0U4B4nYcHc-Fg',
    appId: '1:684530111357:ios:a236b030fa7c52e5797214',
    messagingSenderId: '684530111357',
    projectId: 'recipe-5a6ca',
    storageBucket: 'recipe-5a6ca.appspot.com',
    iosBundleId: 'com.example.receipeGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANKu2K9UvYkcfZOGL-IpjpUp2X2Z5-S94',
    appId: '1:684530111357:web:c439f12a565ddb5b797214',
    messagingSenderId: '684530111357',
    projectId: 'recipe-5a6ca',
    authDomain: 'recipe-5a6ca.firebaseapp.com',
    storageBucket: 'recipe-5a6ca.appspot.com',
  );
}
